applicationID: simple
applicationdesc: A simple example service
applicationowner: uberfx@uber.com

service: 
  timeout: 500
  max_things: 12
  info_prefix: blah

modules:
  http:
    roles: 
      - worker
      - web
    port: 8082
  kafka:
    roles: worker
    zk: http://zk/1234
