applicationID: simple
applicationDesc: A simple example service
applicationOwner: owner@service.com

modules:
  http:
    roles:
      - worker
      - web
    port: 8080
  kafka:
    roles: worker
    zk: http://zk/1234
