applicationID: keyvalue
applicationDesc: A simple keyvalue service
applicationOwner: uberfx@uber.com
modules:
  yarpc:
    advertiseName: keyvalue
    bind: :28941

service:
  some_number: 42

logging:
  stdout: true
  level: info
