applicationID: keyvalue
applicationdesc: A simple keyvalue service
applicationowner: uberfx@uber.com
modules:
  yarpc:
    advertise_name: keyvalue
    bind: :28941

service:
  some_number: 42

logging:
  stdout: true
  level: info
